# Site settings
---
title: Password Studio
description: "Micro site for Passwd Studio API"
# Subpath of your site, e.g. /blog/
baseurl: "/home/"
url: "https://www.passwd.studio"
permalink: /:year/:title
github: "rchapman83"
twitter: "rchapman83"
email: "mail@example.com"
# leave blank if you dont want comments.
disqus-id: ""
# Build settings
markdown: kramdown
sass:
    style: :compressed
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
