---
title: passwd.studio
encoding: UTF-8
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Micro site for Passwd Studio API
baseurl: "/"
url: https://www.passwd.studio
favicon: "/img/html.png"
author: "Rowan Chapman"
github: rchapman83
twitter: rchapman83
disqus-id: passwdstudio
markdown: kramdown
sass:
  style: compressed
plugins:
  - jemoji
  - jekyll-sitemap